# Replace main with the branch name (use find and replace all for convenience)

name: Update latexdiff pdf

on:
  push:
    branches:
    - main
    paths:
    - intro.tex
    - folder1/test.tex

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        file-path: [intro.tex, folder1/test.tex]

    steps:
    - uses: actions/checkout@v2
    - name: latexdiff for ${{ matrix.file-path }}
      with:
        file-path: ${{ matrix.file-path }}
    - name: Install latexdiff
      run: |
        curl -o latexdiff.zip http://ctan.imsc.res.in/support/latexdiff.zip
        unzip latexdiff.zip
        cd latexdiff
        sudo make install
    - name: Save commits into files
      # Save latest commit as new.tex and second latest commit as old.tex
      run: |
        git log -n 1 --pretty=format:"%H" main ${{ matrix.file-path }} | xargs -I{} git show {}:${{ matrix.file-path }} > new.tex
        git log -n 1 --skip 1 --pretty=format:"%H" main ${{ matrix.file-path }} | xargs -I{} git show {}:${{ matrix.file-path }} > old.tex
    - name: Run latexdiff on saved files
      # Run latexdiff on old.tex and new.tex
      run: |
        latexdiff old.tex new.tex > diff.tex
        latexdiff-vc 
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.8.2
      with:
        delete-branch: true
        branch-suffix: short-commit-hash
        commit-message: update pdf
        title: Update pdf
        body: |
            Update pdf
