# Add new file with location under `paths` and `file-path`
# Replace every `main` with the branch name (use find and replace all for convenience)

name: Update latexdiff pdf

on:
  push:
    branches:
    - main
#    paths:
#    - intro.tex
#    - folder1/test.tex

jobs:
  latexdiff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file-path: [intro.tex, folder1/test.tex]

    steps:
    - name: latexdiff for ${{ matrix.file-path }}
      uses: actions/checkout@v2

      # Install latexdiff
    - name: Install latexdiff
      run: |
        curl -o latexdiff.zip http://ctan.imsc.res.in/support/latexdiff.zip
        unzip latexdiff.zip
        cd latexdiff
        sudo make install
        cd ..

      # Save second latest commit as old.tex
    - name: Save commit into a file
      run: |
        ls -a
        git log -n 2 --pretty=format:"%H" main intro.tex | tail -1 | xargs -I{} git show {}:intro.tex > old.tex
        cat old.tex

      # Run latexdiff and save it as a pdf
    - name: Run latexdiff
      run: |
        yes "" | latexdiff-vc --pdf old.tex ${{ matrix.file-path }}

      # Push the pdf
    - name: Push the pdf
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add \*.pdf
        git commit -m "Update ${{ matrix.file-path }} pdf"
        git push